### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by transitive-bullshit** [tungs/timesnap#12]
Hey @tungs, just wanted to say that your work is awesome.

I've played around with similar concepts in [puppeteer-lottie](https://github.com/transitive-bullshit/puppeteer-lottie) and [puppeteer-render-text](https://github.com/transitive-bullshit/puppeteer-render-text), and had wanted to integrate something akin to [ccapture](https://github.com/spite/ccapture.js/) into this type of workflow for awhile.

Do you know if there are any things `ccapture` is overriding that this library isn't handling?

I'm the maintainer of [awesome-puppeteer](https://github.com/transitive-bullshit/awesome-puppeteer) and just added `timesnap` and `timecut` to the list.

Thanks again! 😄

**Comment by tungs** [comment]
Thanks for the kind words!

It looks like ccapture is overriding `HTMLVideoElement.prototype.currentTime` and `HTMLAudioElement.prototype.currentTime`, which this project does not currently do. I haven't really explored trying to overwrite playback of video / audio elements yet, and probably won't anytime soon unless there is some interest in doing so.

The other functions (`requestAnimationFrame`, `setTimeout`, `setInterval`, `performance.now`, `new Date()`, `Date.now`, `cancelAnimationFrame`, `clearTimeout`, and `clearInterval`) are overridden. If they don't work, let me know.

Thanks!

**Comment by Neijin** [comment]
Just wanna say thanks too ! I was going to create a custom solution before I found your package. Nice work !
