### ISSUE TITLE
Recording video meet with iframe

### ISSUE THREAD

**Issue by seanwong1127** [tungs/timesnap#13]
Hi @tungs ,
Thanks for your great job.
I got a problem in timesnap when recording video for a dynamic page.
It goes well before the page create an iframe tag to load another url.
The iframe area results blank in video.
Maybe the new 'preparePageForScreenshot' function can be used to fix it, but I don't know how to implement this.
Can you help?

**Comment by tungs** [comment]
Hi @seanwong1127, thanks for filing this issue! 

Just to confirm, are you dynamically adding an iframe after the page is loaded? Would you happen to have a publicly accessible website that has this issue?

Currently timesnap would not work with a dynamically added iframe after page load. The iframes that are iterated through are collected on page load. I am interested in fixing this, though it might take a while. The fix would involve collecting all the iframes before taking each screenshot (which is pretty easy), but also to synchronize times between the iframes (which would likely require a rewrite of the way time is handled).

**Comment by seanwong1127** [comment]
I fixed the problem with your help.
I create a hidden iframe at first and use it to load pages when needed.
Thanks again.@tungs
