### ISSUE TITLE
Skip frames

### ISSUE THREAD

**Issue by pixarbasim** [tungs/timesnap#26]
Hey there! Thank you for this awesome library.
I wanted to know if there is a way to skip some frames in between. 
From what I understand, this takes a duration and fps and continuously take screenshots till (duration * fps) seconds. 
What I want to achieve is a way to skip some frames in between (the frames that do not change from the previous frame - that logical will be specific to my app). Is there a way to skip over certain frame numbers?

**Comment by tungs** [comment]
Thank you! Right now, if you can use the JavaScript version, you can use the undocumented `config.frameNumToTime` (this isn't available in the command line version). This function should map each captured frame number to a desired capture time. With this implementation, you're not really skipping frames, but rather setting a frame's time to be further apart. As a warning though, at some point, `config.frameNumToTime` may be renamed or changed.

To use it, you'd want to also define `config.frames` to be the total frames you want to capture. Then you defined a function `config.frameNumToTime (frameNumber)` to return what time the frame should be captured, in milliseconds. The frameNumber is one based.

For instance, by the function is:

    frameNumToTime = function (frameCount) {
      return (frameCount-1) * frameDuration;
    };

For instance, if you wanted to capture the first five seconds at 30 frames per second, and the rest at 60 frames per second, you'd have somewhere in the config:

    {
      ...
      frames: 600,
      frameNumToTime: function (frameNumber) {
         // frames 1 - 150 are 30fps
         if (frameNumber <= 150) {
           return (frameNumber - 1) * 1000 / 30;
         } else {
          // afterwards, it is at 60 frames per second
           return (frameNumber - 151) * 1000 / 60 + 5000;
         }
      }
      ...
    }

If you want to do something like frame skipping, off the top of my head, you could do something like:
```
// oldFrameIndex and framesToSkip should both be 1-based (as in this example) or 0 based
var framesToSkip = [3, 45, 46, 87, 90];
var oldFrameIndex = 1;
var skipFrameIndex = 0, currFrameTime = 0;
var numFrames = 600;
var frameTimes = [];
var fps = 60; // need to define fps and frameDuration explicitly here, because frame duration and fps aren't accessible outside of the module
var frameDuration = 1000 / fps; 

for (let i = 1; i <= numFrames; i++) {
  while (skipFrameIndex < framesToSkip.length && oldFrameIndex === framesToSkip[skipFrameIndex]) {
    currFrameTime += frameDuration;
    oldFrameIndex++;
    skipFrameIndex++;
  }
  frameTimes.push(currFrameTime);
  currFrameTime += frameDuration;
  oldFrameIndex++;
}

```
then in your config:

```
{
  ...
  frames: numFrames,
  frameNumToTime: function (frameNumber) {
    return frameTimes[frameNumber - 1]
  }
  ...
}

```

Note that the saved images are going to have sequential frame numbers, without the numbers skipping. Also note that if you use `config.start`, then timesnap adds `config.start` to all the times. So even if `frameNumToTime` returns `0`, the actual time would be `config.start + 0`
