### ISSUE TITLE
screenshot images low quality

### ISSUE THREAD

**Issue by sleepingwheel** [tungs/timesnap#30]
hey, firstly, thanks for Timecut, really great initiative.
however i struggle to produce crispy enough videos, and from the looks of it, the issue originates in screenshot part (timesnap?), not during stitching the images to video with ffmpeg. 

command:
Node timecut/node_modules/timecut/cli.js "https://tungs.github.io/truchet-tiles-original/#autoplay=true&switchStyle=random" --duration=4  --output=vid.mp4 --viewport=1040,1040 

system:
Macos Mojave 10.4.6.

p.s.
if it is caused by Chromium, i'm not sure how to troubleshoot or test that.
how would the specific command look like to change path to chrome from chromium?

**Comment by Asheboy** [comment]
@sleepingwheel You need to add `--executable-path=` followed by the path to chrome. How you find the path to Chrome on OSX, I am not sure!

**Comment by sleepingwheel** [comment]
thanks @Asheboy . managed to launch it via Chrome instead of Chromium. the result is the same fuzzy output. 
Basic screen-capture with Quicktime is much more crisp.

any other tips appreciated.

**Comment by Asheboy** [comment]
@sleepingwheel I've taken the following steps:

```
git clone git@github.com:tungs/timecut.git
cd timecut
yarn install
node cli.js "https://tungs.github.io/truchet-tiles-original/#autoplay=true&switchStyle=random" --duration=4 --output=vid.mp4 --viewport=1040,1040 --executable-path='/usr/bin/google-chrome'
```

and end up with this output https://xfer.clock.co.uk/fW1zL/vid.mp4.

Are you able to try similar and confirm that your issue still persists? Also, can you try running with `--no-headless` to check that the web page renders correctly there?

**Comment by sleepingwheel** [comment]
thanks once again for helping. i checked out your output video and must say although quality is a bit better i still see artifacts that prevent me from calling it good quality recording. Maybe you would agree it does look a bit fuzzy.  i dont expect lossless quality though.  
maybe the problem is deeper, connected to timesnap? previously i noticed that it is specifically the screenshots, not the ffmpeg conversion that is fuzzy.

Comparing timecut with default quicktime recording:
<img width="979" alt="timecut-vs-quicktime" src="https://user-images.githubusercontent.com/52998808/72056217-7bcd7100-32cc-11ea-8041-02cf28234532.png">

**Comment by Asheboy** [comment]
@sleepingwheel I've had a look at it in headed mode and the artifacting looks to be being rendered by Chrome, rather than being an consequence of the screen shotting. Have you got a different webpage that you can record to see if it fits your purpose?

**Comment by sleepingwheel** [comment]
I get the same with every website.
yeah i ran timecut with --no-headless, and in that mode chrome/chromium seem to be zooming in or out for every screenshot. or at least that's what i saw on my screen during recording. not sure if that the way it supposed to be. 

but i guess the key here is that your output is roughly the same as mine. maybe better quality is not even available?

the same commands on different website: timecut vs quicktime:
<img width="914" alt="Screenshot 2020-01-09 at 13 37 45" src="https://user-images.githubusercontent.com/52998808/72068455-5ef16780-32e5-11ea-95b3-606344804bcb.png">

**Comment by Asheboy** [comment]
@sleepingwheel I see what you mean. I imagine that QuickTime uses Safari and manages to get hold of something better than screenshots to render that quality.

`and in that mode chrome/chromium seem to be zooming in or out for every screenshot` - I have only ever seen this when using `deviceScaleFactor` which isn't supported by timesnap currently, so it's funny that you've experienced it here. `deviceScaleFactor` is actually something that may help you. Below I have two 1920x1080 images, one with deviceScaleFactor of 1 and another with deviceScaleFactor of 2. Can you confirm if the second is of good enough quality for you?

### deviceScaleFactor 1
![image-000000010](https://user-images.githubusercontent.com/1822529/72111879-e8c82180-3333-11ea-8a9b-a2ba27e8b39f.png)

### deviceScaleFactor 2
![image-000000010](https://user-images.githubusercontent.com/1822529/72111841-d64de800-3333-11ea-816a-b4bbb9a895dd.png)

On another note, have you reviewed the screenshots which are taken by using `--keep-frames`? It should leave a temporary directory in the root of the project. Can you check if these are perhaps better quality? It could be degradation from FFMPEG which is causing some of your issue too.

Thanks for trying these things out for me!

**Comment by tungs** [comment]
Thanks for filing this! Just to confirm, when you're capturing with QuickTime, are you capturing a Chrome window? The zooming in and out sounds peculiar. Could you record a video (or show an image of the zoom in) of that too?

And as @Asheboy mentioned, using the --keep-frames in `timecut` should keep the original, lossless frames from `timesnap`, which should give you an idea of how much is lost in video compression.

There may be a puppeteer option to improve screenshot quality for OS X, but I didn't find it from a quick web search. @Asheboy's mention of deviceScaleFactor sounds like a promising workaround.

**Comment by sleepingwheel** [comment]
thanks both, 
regarding the zooming in-out during no-headless mode, attaching a video of that with --no-headless mode:
https://vimeo.com/383965970


regarding deviceScaleFactor, 
would this be the correct command then? does not seem to make a difference to me, but in your #2 screenshot it does look sharper. am i using it incorrectly?
Node timecut/node_modules/timecut/cli.js "https://youtube.com" --duration=2  --output=devicescale.mp4 --viewport=1040,1040  --deviceScaleFactor=2

and yes i can confirm it is the images in the temp folder that are fuzzy, so it does not seem to be ffmpeg fault.

**Comment by Asheboy** [comment]
@sleepingwheel deviceScaleFactor is not implemented in timesnap currently, so you're unable to test it yourself without making code changes. I can detail these if you'd like?

Regarding the zooming, do you still get this if you set your `--viewport` to be your full screen resolution? It would be interesting to see if this has any quality changes for you too.

**Comment by sleepingwheel** [comment]
>>I can detail these if you'd like?
we can try that, sure. the more details, the better please. 

zooming, 
yes i get the same if i dont set --viewport parameter or i set it to my full resolution.

**Comment by Asheboy** [comment]
@sleepingwheel Change this line https://github.com/tungs/timesnap/blob/master/index.js#L161 to:

```
return page.setViewport({ width: 1920, height: 1080, deviceScaleFactor: 2 });
```

and then run as normal. It will ignore your `--viewport` option and use `1920,1080` instead.

**Comment by tungs** [comment]
Instead of modifying the source, you can also set puppeteer/Chromium/Chrome specific arguments via the [--launch-arguments](https://github.com/tungs/timesnap#cli-options-launch-arguments) option. So instead of `--deviceScaleSactor=2` you could use `--launch-arguments="--device-scale-factor=2"`, or alternatively `--launch-arguments="--force-device-scale-factor=2"`. I'm not exactly sure what the difference is with the `force` prefix.

You can find a whole list of arguments [here](https://peter.sh/experiments/chromium-command-line-switches/). Some may lead to better screenshot quality, though the issue may just be from how puppeteer works on OS X.

Thanks for posting the video link, it's really helpful for understanding what may be going on. It looks like the zooming is occurring under each screenshot capture, though I'm not why that's the case yet.

**Comment by tungs** [comment]
It looks like other people have had issues with puppeteer's screenshot quality (see puppeteer/puppeteer#1469). The solution offered there is to alter the device scale factor too.

**Comment by victorrseloy** [comment]
I had a similar problem and the this MR fixed the problem. Do you have plans to merge it @tungs ?

**Comment by tungs** [comment]
Hi @victorrseloy, thanks for your interest and bringing this to my attention! PR #40 looks useful since it affects screenshot quality, and I'll try to get it merged in the next two weeks.

**Comment by tungs** [comment]
This enhancement should have been added in [version 0.2.0](https://github.com/tungs/timesnap/releases/tag/v0.2.0). It can be invoked via something like `--viewport="800,600,deviceScaleFactor=2"`.

Feel free to comment or file a new issue if there are still quality issues.
