### ISSUE TITLE
Quiet mode doesn't work in NodeJS

### ISSUE THREAD

**Issue by seifsg** [tungs/timesnap#34]
Keeps logging to the console even after setting quite mode to true

Code that is currently being used:
```javascript   
const r = await timecut({
      canvasCaptureMode: true,
      duration,
      fps: parseInt(FPS),
      frameCache: true,
      viewport: {
        height: 1920,
        width: 1080,
      },
      url: "http://localhost:3000/s/" + newPathID + "/i.html",
      output,
      selector: "#canvas",
      quite: true,
    });
```

**Comment by tungs** [comment]
Hi @seifsg, could you verify that you're typing `quiet` mode in correctly? You have spelled it `quite` here. Thanks!

**Comment by seifsg** [comment]
You are absolutely right, and I was wondering why when in the code it had no other way to define the logging function.
I apologize for my mistake. Thank you for your help!
