### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gabigarcez** [tungs/timesnap#58]
**Describe the bug**
If I take a screenshot using Puppeteer only, I get perfect colors. When using timesnap, dithering occurs and the colors become blocky and incorrect. 

EDIT: another thing I just noticed is this color corruption doesn't happen when headless is false.

`await timesnap({
        url: "http://localhost:8080",
        selector: "#container",
        fps: 13,
        duration: 8,
        outputDirectory: dir,
        headless: true,
        viewport: {
          width: 600,
          height: 800
        }
      });`

Here are the screenshots results when I use puppeteer only and then when I use timesnap, respectively.

![expected](https://user-images.githubusercontent.com/36829331/116801233-16784180-ab08-11eb-8975-6ecabe9f466d.png)
![result](https://user-images.githubusercontent.com/36829331/116801232-15dfab00-ab08-11eb-95af-6e0588c1668e.png)

How can I fix this?

**Comment by gabigarcez** [comment]
I would imagine a workaround would be using canvasCaptureMode but I cannot get it to work on my WebGL canvas either.

**Comment by gabigarcez** [comment]
Changing my webgl canvas settings seems to have solved the problem.

```
const gl = canvas.getContext('webgl', {
   premultipliedAlpha: false,
   preserveDrawingBuffer: true
})
```

**Comment by tungs** [comment]
Thanks for sharing this problem and solution!

For others encountering this sort of problem, using [`canvasCaptureMode`](https://github.com/tungs/timesnap#js-config-canvas-capture-mode)/[`--canvas-capture-mode`](https://github.com/tungs/timesnap#cli-options-canvas-capture-mode) with the immediate prefix (e.g. `'immediate:png'`), might help.
