### ISSUE TITLE
Add prepare function called before the screenshot

### ISSUE THREAD

**Issue by yarres** [tungs/timesnap#6]
Hi,

The use case is to overwrite the html template before the screenshots, by using `page.evaluate()`

For example, add the following lines after the page is loaded (after `page.goto()`):
```javascript
 .then(function() {
            log('Page loaded');
            // Custom function loaded before capture
            return config.prepare(page);
          })
```
The `prepare` function can then be added to the config in order to do for example:  
```javascript
 timesnap({
...
prepare(page) {
return page.evaluate(
      ({
        customTextSelector,
        customTextColor
      }) => {
          const textElement: HTMLElement = document.querySelector(
          customTextSelector,
        );
        // Change the color
        textElement.style.color = customTextColor;
      },
      {
        customTextSelector,
        customTextColor
      },
    );
}
})
```

What do  you think about it?

Thanks!

**Comment by tungs** [comment]
Sounds like a useful, flexible enhancement! For verbosity I'll probably name it something like `preparePage`.

Just to clarify for your use case, this function is only ran once, after the page is loaded, and not before every screen shot?

**Comment by yarres** [comment]
To be more precise, my use case  is to dynamically modify the html page one time before rendering.
For example, I have a predefined html animation with a text "I am a general purpose animation" which I would like to be able to change dynamically. But the change would be made just one time, before the screenshot taking phase has started.

**Comment by yarres** [comment]
I added a [PR](https://github.com/tungs/timesnap/pull/7).
Tell me what you think about it when you have time.
Thanks!
