### ISSUE TITLE
[FEATURE REQUEST] Take screenshots from client on demand

### ISSUE THREAD

**Issue by svk014** [tungs/timesnap#63]
**Is your feature request related to a problem? Please describe.**

- I need to take pictures of a website only when the content changes.
- The content is not guaranteed to change periodically, but the delay is not longer than a few seconds.
- And, it is imperative that I do not take duplicate screenshots

**Describe the solution you'd like**
Would it possible to add a feature that allows the client to call a function to take a screenshot, instead of screenshots being taken at a uniform frame rate. This could work very well the newly introduced `stopFunctionName` feature.

One could pass a config name something like `nextScreenshotFunctionName`.
And, on the client the function could be called with an optional `outputPath` argument. Like this
```
nextScreenshotFunctionName('path/filename.extension')
```

**Comment by tungs** [comment]
I think there are two ways to think about this: selectively capturing frames and capturing frames on demand. One is currently possible, the other not so much.

### Selectively Capturing Frames
You may already be able to achieve the functionality you want with the passable function called [`config.shouldSkipFrame`](https://github.com/tungs/timesnap#js-config-should-skip-frame), which tells `timesnap` whether to skip a current frame. You can use the `page` property to evaluate for various conditions. For instance, you could use [`page.evaluate`](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#pageevaluatepagefunction-args) to check to skip the frame:

```
timesnap({
  //...
  shouldSkipFrame: async function ({ page }) {
    return page.evaluate(async function () {
      // frameChanged is set somewhere else, or you could use custom logic here
      var shouldSkip = !frameChanged;
      frameChanged = false;
      return shouldSkip;
    })
  }
  // ...
})
```
Note that the saved frames will still have their original frame numbers (e.g. `002.png` and `005.png` even if there are only two frames saved).

### On Demand Capturing
If, on the other hand, you want to have a function callable from the client web page to take a screenshot, there are some issues with this:
  * Snapshots / Capturing is initiated on the `puppeteer`/`node` side of things, which would be called asynchronously from the client web page.
    * I believe the asynchronous nature makes it so that if you have multiple screenshots from a blocking loop, they'll all be taken after the loop finishes. Also there can be canvas/screenshot issues in some modes if they're not captured immediately
    * The current implementation in `timeweb` traverses the virtual timeline in a blocking manner. I think it would need some condition to relinquish its iteration (this would be a nice feature to have, though it's not implemented yet) so puppeteer could take a screenshot. I also don't know how precise puppeteer would be in getting called-- for all I know, it might miss being called when `timeweb` relinquishes.
  * The idea itself is a little outside of the scope of the project

Let me know whether or not the `shouldSkipFrame` approach would work. In general, it does sound like it's the sort of thing to do with just `puppeteer` and `timeweb` (though I haven't yet written a tutorial/article on that, and `timeweb` would need that aforementioned feature).

**Comment by svk014** [comment]
Thank you for your response. I think I can achieve the desired functionality using `shouldSkipFrame` config. It had not occurred to me that I could use puppeteer in conjunction with timesnap API.

**Comment by tungs** [comment]
Sure thing, it certainly isn't obvious that this would be the way to go about things. I do appreciate you filing this; it articulates a clear feature / use case and makes me think about the underlying challenges behind implementing it.
