### ISSUE TITLE
Stopping capture

### ISSUE THREAD

**Issue by abushnaq-work** [tungs/timesnap#67]
Hi @tungs 

Do you have an example somewhere of how to use `stopFunctionName` ? I want to have multiple instances where some of them just quit and go away after a certain frame instead of going through the rest of the animation needlessly. 

In other words, I'm looking for the following scenario: if I have frames 1-600, I create let's say 6 instances of timesnap, each one instructed to process a given hundred and skip capturing the rest. But for the one from 1-100, I want to use the stop function to just have it finish and shutdown entirely. That's what I'm looking for with `stopFunctionName` but not sure how to use it?

Thanks!

**Comment by tungs** [comment]
Hi @abushnaq-work,

`stopFunctionName` isn't quite meant to do that. It creates a function that's accessible on your web page to stop capture (for example, if `config.stopFunctionName = 'stopCapture';` in your web page you can run `stopCapture()` to stop capturing).

Instead, for this particular case, you can probably just alter `config.frames` or `config.duration` to match the end number of frames for each particular instance.

**Comment by tungs** [comment]
Yes, it isn't clear, but `config.frames` counts both skipped and unskipped frames. If you wanted to capture frames 200-400, you'd use a `config.frames` value of 400, and then use `shouldSkipFrame` to skip the first 200.

**Comment by abushnaq-work** [comment]
Got it thanks.
